namespace ErrorCode {
	enum Code {
		CANNOT_OPEN_CON = 101,	
		CONNECT_REFUSED	= 111,	
		SYSTEM_HLP_RPLY	= 211,
		SRVC_RUN_SUCCES = 220,
		SERVICE_CLOSING = 221,
		AUTH_SUCCESSFUL = 235,	
		REQUEST_SUCCESS	= 250,	
		USRNOTLCL_RELAY = 251,	
		CANT_VERIFY_USR = 252,	
		START_MAIL_DATA = 354,	
		SERVC_NOT_AVABL	= 421,	
		OUT_MSG_TIMEOUT	= 447,	
		CMD_SYNTAX_EROR	= 500,
		AUTH_UNSUCESFUL = 504	
	};

	char* getCodeDescription( Code _code ); 
	
};
